# Generated by Django 2.2.6 on 2022-02-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220202_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date'], 'verbose_name': 'AAAAAAAAAAAAAAAAAAAA'},
        ),
    ]
